src/Rad/ProductBundle/Entity/Product.php
<?php

namespace Rad\ProductBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Rad\MagentoConfigBundle\Entity\AttributeSet;
use Rad\MagentoConfigBundle\Entity\Category;
use Rad\MagentoConfigBundle\Entity\Color;
use Rad\MagentoConfigBundle\Entity\CreativeDesigner;
use Rad\MagentoConfigBundle\Entity\DesignPlace;
use Rad\MagentoConfigBundle\Entity\FashionAccount;
use Rad\MagentoConfigBundle\Entity\Gender;
use Rad\MagentoConfigBundle\Entity\Manufacturer;
use Rad\MagentoConfigBundle\Entity\Origin;
use Rad\MagentoConfigBundle\Entity\PrintingMethod;
use Rad\MagentoConfigBundle\Entity\Structure;
use Rad\MagentoConfigBundle\Entity\Support;
use Rad\MagentoConfigBundle\Entity\TextLang;
use Rad\MagentoConfigBundle\Entity\Typography;
use Rad\PageBundle\Interfaces\UploadedFiles;
use Symfony\Component\Validator\Constraints as Assert;
use Rad\PageBundle\Traits;

/**
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="Rad\ProductBundle\Repository\ProductRepository")
 */
class Product implements UploadedFiles {
    use Traits\Id;
    use Traits\Timestamps;
    use Traits\Name;

    /**
     * @var \DateTime
     * @Assert\NotBlank
     * @ORM\Column(type="datetime", name="online_date")
     */
    protected $onlineDate;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="\Rad\MagentoConfigBundle\Entity\Country")
     */
    protected $countries;

    /**
     * @var Support
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Support", inversedBy="products")
     */
    protected $support;

    /**
     * @var Gender
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Gender")
     */
    protected $gender;

    /**
     * @var DesignPlace
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\DesignPlace")
     */
    protected $designPlace;

    /**
     * @var Structure
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Structure")
     */
    protected $structure;

    /**
     * @var Typography
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Typography")
     */
    protected $typography;

    /**
     * @var TextLang
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\TextLang")
     */
    protected $textLang;

    /**
     * @var Origin
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Origin")
     */
    protected $origin;

    /**
     * @var FashionAccount
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\FashionAccount")
     */
    protected $fashionAccount;

    /**
     * @var CreativeDesigner
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\CreativeDesigner")
     */
    protected $creativeDesigner;

    /**
     * @var Manufacturer
     * @Assert\NotBlank
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Manufacturer")
     */
    protected $manufacturer;

    /**
     * @var Color
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\Color")
     */
    protected $color;

    /**
     * @var PrintingMethod
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\PrintingMethod")
     */
    protected $printingMethod;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, name="bought_price")
     */
    protected $boughtPrice = 0;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, name="sell_price")
     */
    protected $sellPrice;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, name="artist_amount")
     */
    protected $artistAmount;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=2, name="special_price")
     */
    protected $specialPrice;

    /**
     * @var ProductFieldTranslated
     * @ORM\OneToMany(targetEntity="ProductFieldTranslated", mappedBy="product", cascade="all")
     */
    protected $translations;

    /**
     * @Assert\Image
     */
    protected $thumbnail;

    /**
     * @Assert\Image
     */
    protected $smallImage;

    /**
     * @Assert\Image
     */
    protected $image;

    /**
     * @Assert\Image
     */
    protected $flatImage;

    /**
     * @ORM\Column(type="string", nullable=true, name="thumbnail_path")
     */
    protected $thumbnailPath;

    /**
     * @ORM\Column(type="string", name="small_image_path", nullable=true)
     */
    protected $smallImagePath;

    /**
     * @ORM\Column(type="string", name="image_path", nullable=true)
     */
    protected $imagePath;

    /**
     * @ORM\Column(type="string", name="flat_image_path", nullable=true)
     */
    protected $flatImagePath;


    /**
     * @ORM\Column(type="string", name="sku_begin", nullable=true)
     *
     */
    protected $skuBegin;

    /**
     * @ORM\ManyToMany(targetEntity="\Rad\MagentoConfigBundle\Entity\Category")
     */
    protected $categories;

    /**
     * @ORM\Column(type="boolean", nullable=false, name="ready_synchronization")
     */
    protected $readySynchronization;

    /**
     * @ORM\Column(type="datetime", nullable=true, name="synchronizedAt")
     */
    protected $synchronizedAt;

    /**
     * @ORM\OneToMany(targetEntity="MagentoProduct", mappedBy="product")
     */
    protected $magentoProducts;

    /**
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\AttributeSet")
     */
    protected $attributeSet;

    /**
     * @ORM\Column(type="boolean", name="is_pretreated")
     */
    protected $isPretreated;

    /**
     * @ORM\Column(type="integer", name="design_cost_category", nullable=true)
     */
    protected $designCostCategory;

    /**
     * @ORM\ManyToOne(targetEntity="\Rad\MagentoConfigBundle\Entity\DesignColor")
     */
    protected $designColor;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $online;

    /**
     * @ORM\Column(type="string")
     */
    protected $fullSku;

    public static function fieldToTranslate()
    {
        return array(
            'sellPrice',
            'specialPrice',
            'name'
        );
    }

    /**
     * @return array
     */
    public function getFileFields()
    {
        return array(
            'thumbnail',
            'smallImage',
            'image',
            'flatImage'
        );
    }

    /**
     * Product constructor.
     */
    public function __construct()
    {
        $this->translations             = new ArrayCollection();
        $this->categories               = new ArrayCollection();
        $this->countries                = new ArrayCollection();
        $this->magentoProducts          = new ArrayCollection();
        $this->readySynchronization     = false;
        $this->online                   = false;
    }

    public function getFullSKU()
    {
        if (!$this->fullSku) {
            $this->setFullSKU();
        }
        return $this->fullSku;
    }

    public function setFullSKU()
    {
        $this->fullSku = implode('_', array(
            $this->getSkuBegin(),
            $this->getSupport() ? $this->getSupport()->getName() : '',
            $this->getColor() ? $this->getColor()->getSkuName() : ''
        ));

        return $this;
    }

    /**
     * Set boughtPrice
     *
     * @param string $boughtPrice
     *
     * @return Product
     */
    public function setBoughtPrice($boughtPrice)
    {
        $this->boughtPrice = $boughtPrice;

        return $this;
    }

    /**
     * Get boughtPrice
     *
     * @return string
     */
    public function getBoughtPrice()
    {
        return $this->boughtPrice;
    }

    /**
     * Set sellPrice
     *
     * @param string $sellPrice
     *
     * @return Product
     */
    public function setSellPrice($sellPrice)
    {
        $this->sellPrice = $sellPrice;

        return $this;
    }

    /**
     * Get sellPrice
     *
     * @return string
     */
    public function getSellPrice()
    {
        return $this->sellPrice;
    }

    /**
     * Set artistAmount
     *
     * @param string $artistAmount
     *
     * @return Product
     */
    public function setArtistAmount($artistAmount)
    {
        $this->artistAmount = $artistAmount;

        return $this;
    }

    /**
     * Get artistAmount
     *
     * @return string
     */
    public function getArtistAmount()
    {
        return $this->artistAmount;
    }

    /**
     * Add country
     *
     * @param \Rad\MagentoConfigBundle\Entity\Country $country
     *
     * @return Product
     */
    public function addCountry(\Rad\MagentoConfigBundle\Entity\Country $country)
    {
        $this->countries[] = $country;

        return $this;
    }

    /**
     * Remove country
     *
     * @param \Rad\MagentoConfigBundle\Entity\Country $country
     */
    public function removeCountry(\Rad\MagentoConfigBundle\Entity\Country $country)
    {
        $this->countries->removeElement($country);
    }

    /**
     * Get countries
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCountries()
    {
        return $this->countries;
    }

    /**
     * Set support
     *
     * @param \Rad\MagentoConfigBundle\Entity\Support $support
     *
     * @return Product
     */
    public function setSupport(\Rad\MagentoConfigBundle\Entity\Support $support = null)
    {
        $this->support = $support;
        $this->setFullSKU();

        return $this;
    }

    /**
     * Get support
     *
     * @return \Rad\MagentoConfigBundle\Entity\Support
     */
    public function getSupport()
    {
        return $this->support;
    }

    /**
     * Set color
     *
     * @param \Rad\MagentoConfigBundle\Entity\Color $color
     *
     * @return Product
     */
    public function setColor(\Rad\MagentoConfigBundle\Entity\Color $color = null)
    {
        $this->color = $color;
        $this->setFullSKU();

        return $this;
    }

    /**
     * Get color
     *
     * @return \Rad\MagentoConfigBundle\Entity\Color
     */

src/Rad/ProductBundle/Controller/ProductController.php
<?php

namespace Rad\ProductBundle\Controller;

use Rad\MagentoConfigBundle\Entity\PrintingMethod;
use Rad\ProductBundle\Entity\Product;
use Rad\PageBundle\Controller\BaseController;
use Rad\ProductBundle\Entity\ProductFieldTranslated;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends BaseController
{
    protected $viewData = array();

    public function indexAction(Request $request)
    {
        $em = $this->get('doctrine.orm.entity_manager');

        $dql = 'SELECT e FROM ' . $this->getEntityName() . ' e';
        $query = $em->createQuery($dql);
        $search = $request->get('q');
        if ($search) {
            $query = $this->getDoctrine()->getRepository($this->getEntityClass())->search($search, 'e');
        }

        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            intval($this->getParameter('item_per_page'))
        );

        return $this->render($this->getBaseTemplate() . ':index.html.twig', array(
            'pagination'    => $pagination,
            'base_route'    => $this->getBaseRoute(),
            'base_template' => $this->getBaseTemplate()
        ));
    }

    public function showAction(Product $product)
    {
        return $this->render(
            $this->getBaseTemplate() . ':show.html.twig',
            array('product' => $product, 'base_route' => $this->getBaseRoute())
        );
    }

    protected function setViewData()
    {
        $prints = $this->getDoctrine()->getManager()->getRepository('RadMagentoConfigBundle:PrintingMethod')->findAll();

        /** @var PrintingMethod $print */
        foreach ($prints as $print) {
            if (in_array(strtolower($print->getName()), $this->getParameter('magento_pretreated_labels'))) {
                if (!isset($this->viewData['pretreated'])) {
                    $this->viewData['pretreated'] = array();
                }
                $this->viewData['pretreated'][] = $print;
            }
            if (in_array(strtolower($print->getName()), $this->getParameter('magento_design_cost_category_labels'))) {
                if (!isset($this->viewData['design_cost_category'])) {
                    $this->viewData['design_cost_category'] = array();
                }
                $this->viewData['design_cost_category'][] = $print;
            }
            if (in_array(strtolower($print->getName()), $this->getParameter('magento_design_color_labels'))) {
                if (!isset($this->viewData['design_color'])) {
                    $this->viewData['design_color'] = array();
                }
                $this->viewData['design_color'][] = $print;
            }
        }
    }

    public function fieldsAction(Request $request, Product $product)
    {
        if ($request->isMethod('POST')) {
            $ret = array('errors' => array());
            foreach ($request->request as $id => $value) {
                if (!$this->updateField($id, $value)) {
                    $ret['errors'][] = $id;
                }
            }
            $this->getDoctrine()->getManager()->flush();

            if (empty($ret['errors'])) {
                $ret['url'] = $this->container->get('router')->generate('rad_product_index');

                $queue = $request->getSession()->get('redirection_queue', array());
                if (!empty($queue)) {
                    $item = array_shift($queue);
                    $request->getSession()->set('redirection_queue', $queue);
                    if ($item['msg']) {
                        $this->get('braincrafted_bootstrap.flash')->error($item['msg']);
                    }
                    $ret['url'] = $item['url'];
                }
            }
            return new JsonResponse($ret);
        }
        return $this->render($this->getBaseTemplate() . ':fields.html.twig', array('product' => $product));
    }

    public function updateField($id, $value)
    {
        /** @var ProductFieldTranslated $item */
        $item = $this->getDoctrine()->getManager()->find('Rad\ProductBundle\Entity\ProductFieldTranslated', $id);
        $item->setValue($value);

        return count($this->get('validator')->validate($item)) ? false : true;
    }

    public function getFormHandler()
    {
        return $this->get('rad.product.form.handler');
    }

    public function synchronizeAction()
    {
        $ret = $this->get('rad.product.synchronization')->process();
        if (!$ret || empty($ret)) {
            $this->get('braincrafted_bootstrap.flash')->error('No product to synchronize');
        }
        else {
            $this->get('braincrafted_bootstrap.flash')->success('Products synchronized: ' . implode('<br />', $ret));
        }
        return $this->redirectToRoute($this->getBaseRoute() . '_index');
    }

    public function createAction()
    {
        $this->setViewData();
        return $this->renderForm(new Product(), 'create');
    }

    public function editAction(Product $product)
    {
        $this->setViewData();
        return $this->renderForm($product, 'edit');
    }

    public function deleteAction(Product $product)
    {
        return $this->_delete($product);
    }

    public function getBaseTemplate()
    {
        return 'RadProductBundle:Product';
    }

    public function getEntityClass()
    {
        return '\Rad\ProductBundle\Entity\Product';
    }

    public function getEntityName()
    {
        return 'RadProductBundle:Product';
    }

    public function getFormName()
    {
        return 'rad_productbundle_product';
    }

    public function getBaseRoute()
    {
        return 'rad_product';
    }
}

src/Rad/ProductBundle/Resources/views/Product/_form.html.twig
{% macro serialize_id(items) %}{% set comma='' %}{% for item in items %}{{ comma ~ item.id }}{% set comma=',' %}{% endfor %}{% endmacro %}

{{ form_start(form, { 'style': 'horizontal' }) }}
    {{ form_errors(form) }}

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <i class="glyphicon glyphicon-tags"></i> &nbsp; &nbsp; Global informations
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                {{ form_row(form.countries) }}
                {{ form_row(form.support) }}
                {{ form_row(form.color) }}
                {{ form_row(form.onlineDate) }}
                <div id="printingmethod">{{ form_row(form.printingMethod) }}</div>

                <div id="printingmethod-depends">
                    {% if pretreated is defined %}
                        <div data-dependents="{{ _self.serialize_id(pretreated) }}">{{ form_row(form.isPretreated) }}</div>
                    {% endif %}
                    {% if design_cost_category is defined %}
                        <div data-dependents="{{ _self.serialize_id(design_cost_category) }}">{{ form_row(form.designCostCategory) }}</div>
                    {% endif %}
                    {% if design_color is defined %}
                        <div data-dependents="{{ _self.serialize_id(design_color) }}">{{ form_row(form.designColor) }}</div>
                    {% endif %}
                </div>

            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <i class="glyphicon glyphicon-barcode"></i> &nbsp; &nbsp; Price informations
                    </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">
                    {#{{ form_row(form.boughtPrice,  { 'input_group': { 'prepend': '$/€/£' } }) }}#}
                    {{ form_row(form.sellPrice,    { 'input_group': { 'prepend': '$/€/£' } }) }}
                    {{ form_row(form.specialPrice, { 'input_group': { 'prepend': '$/€/£' } }) }}
                    {{ form_row(form.artistAmount, { 'input_group': { 'prepend': '%' } }) }}
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingThree">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        <i class="glyphicon glyphicon-list-alt"></i> &nbsp; &nbsp; Product informations
                    </a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body">
                    {{ form_row(form.name) }}
                    {{ form_row(form.skuBegin) }}
                    {{ form_row(form.categories) }}
                    {{ form_row(form.gender) }}
                    {{ form_row(form.designPlace) }}
                    {{ form_row(form.structure) }}
                    {{ form_row(form.typography) }}
                    {{ form_row(form.textLang) }}
                    {{ form_row(form.origin) }}
                    {{ form_row(form.fashionAccount) }}
                    {{ form_row(form.creativeDesigner) }}
                    {{ form_row(form.attributeSet) }}
                    <div data-select2-element>{{ form_row(form.manufacturer) }}</div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingFor">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFor" aria-expanded="false" aria-controls="collapseFor">
                        <i class="glyphicon glyphicon-camera"></i> &nbsp; &nbsp; Images / Fichiers
                    </a>
                </h4>
            </div>
            <div id="collapseFor" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFor">
                <div class="panel-body">
                    <div>
                        {{ form_row(form.thumbnail) }}
                        {% if item.thumbnailPath %}
                            <div class="col-lg-offset-2">
                                <img height="50" src="{{ asset('uploads/' ~ item.thumbnailPath) | default('') }}" />
                            </div>
                        {% endif %}
                    </div>
                    <div>
                        {{ form_row(form.smallImage) }}
                        {% if item.smallImagePath %}
                            <div class="col-lg-offset-2">
                                <img height="50" src="{{ asset('uploads/' ~ item.smallImagePath) | default('') }}" />
                            </div>
                        {% endif %}
                    </div>
                    <div>
                        {{ form_row(form.image) }}
                        {% if item.imagePath %}
                            <div class="col-lg-offset-2">
                                <img height="50" src="{{ asset('uploads/' ~ item.imagePath) | default('') }}" />
                            </div>
                        {% endif %}
                    </div>
                    <div>
                        {{ form_row(form.flatImage) }}
                        {% if item.flatImagePath %}
                            <div class="col-lg-offset-2">
                                <img height="50" src="{{ asset('uploads/' ~ item.flatImagePath) | default('') }}" />
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ form_row(form.readySynchronization) }}
    {{ form_rest(form) }}
    <br />
    <br />
    <div class="text-center"><input type="submit" class="btn btn-primary btn-lg" value="Submit"></div>
    <br />
    <br />
{{ form_end(form) }}

<script type="text/javascript">
    jQuery(function($){
        $('[data-select2-element] select').select2();
        setTimeout(function(){
            $('#rad_productbundle_product_categories').parent().find('span.select2-container').css('width', '100%');
            $('[data-select2-element] span.select2-container').css('width', '100%');
        }, 1000);
        var depends = $('#printingmethod-depends [data-dependents]');
        $('#printingmethod select')
                .select2()
                .change(function(){
                    var value = $(this).val();
                    depends.each(function(){
                        var $this = $(this);
                        if ($this.attr('data-dependents').split(',').indexOf(value) == -1) {
                            $this.hide();
                        }
                        else {
                            $this.show();
                        }
                    });
                })
                .change()
        ;

        {#
                <div id="printingmethod">{{ form_row(form.printingMethod) }}</div>

                <div id="printingmethod-depends">
                    {% if pretreated is defined %}
                        <div data-dependents="{{ _self.serialize_id(pretreated) }}">{{ form_row(form.isPretreated) }}</div>
                    {% endif %}
                    {% if design_cost_category is defined %}
                        <div data-dependents="{{ _self.serialize_id(design_cost_category) }}">{{ form_row(form.designCostCategory) }}</div>
                    {% endif %}
                    {% if design_color is defined %}
                        <div data-dependents="{{ _self.serialize_id(design_color) }}">{{ form_row(form.designColor) }}</div>
                    {% endif %}
                </div>
#}
    });
</script>

src/Rad/ProductBundle/Resources/views/Product/create.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <h1>New Product</h1>
        {% include 'RadProductBundle:Product:_form.html.twig' %}
    </div>

{% endblock %}

src/Rad/ProductBundle/Resources/views/Product/edit.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <h1>
            Edit <em>{{ item }}</em>
            <span class="pull-right btn-group">
                {#<a class="btn btn-danger" href="{{ path(base_route ~ '_delete', {'id': item.id}) }}">Delete <i class="glyphicon glyphicon-trash"></i></a>#}
                <a class="btn btn-info" href="{{ path('rad_product_fields', {'product': item.id}) }}">Edit fields <i class="glyphicon glyphicon-pencil"></i></a>
                <a class="btn btn-primary" href="{{ path('rad_product_show', {'product': item.id}) }}">Show details <i class="glyphicon glyphicon-eye-open"></i></a>
            </span>
        </h1>
        {% include 'RadProductBundle:Product:_form.html.twig' %}
    </div>
{% endblock %}

src/Rad/ProductBundle/Resources/views/Product/index.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <h1>
            Product list ({{ pagination.getTotalItemCount }})
            <span class="pull-right">
                <a href="{{ path(base_route ~ '_create') }}" class="btn btn-success">Add <i class="glyphicon glyphicon-plus"></i></a>
                <a href="{{ path(base_route ~ '_synchronize') }}" class="btn btn-info">Synchronize <i class="glyphicon glyphicon-refresh"></i></a>
            </span>
        </h1>
        <table class="table table-striped">
            <tr>
                <th{% if pagination.isSorted('e.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Name', 'e.name') }}</th>
                <th{% if pagination.isSorted('e.sellPrice') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Price', 'e.sellPrice') }}</th>
                <th{% if pagination.isSorted('e.specialPrice') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Special Price', 'e.specialPrice') }}</th>
                <th{% if pagination.isSorted('e.readySynchronization') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Ready to synchornize', 'e.readySynchronization') }}</th>
                <th{% if pagination.isSorted('e.synchronizedAt') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Synchronize date', 'e.synchronizedAt') }}</th>
                <th{% if pagination.isSorted('e.gender.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Gender', 'e.gender.name') }}</th>
                <th{% if pagination.isSorted('e.support.name') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Support', 'e.support.name') }}</th>
                <th>Categories</th>
                <th>Stores</th>
                <th>Actions</th>
            </tr>
            {% for item in pagination %}
                <tr>
                    <td>{{ item }}<br />{{ item.fullSKU }}</td>
                    <td>{{ item.sellPrice }}</td>
                    <td>{{ item.specialPrice }}</td>
                    <td>{{ item.readySynchronization ? 'Yes' : 'No' }}</td>
                    <td>{{ item.synchronizedAt ? item.synchronizedAt | date : '' }}</td>
                    <td>{{ item.gender }}</td>
                    <td><a href="{{ path('rad_magento_admin_support_edit', {'id':item.support.id}) }}">{{ item.support }}</a></td>
                    <td>
                        <ul>
                            {% for category in item.categories %}
                                <li>{{ category }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <th>{% for country in item.countries %}{{ loop.index0 > 0 ? ', ' : '' }}{{ country }}{% endfor %}</th>
                    <td>
                        <span class="btn-group">
                            <a href="{{ path(base_route ~ '_edit', {'id':item.id}) }}" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                            <a href="{{ path(base_route ~ '_fields', {'product':item.id}) }}" class="btn btn-info"><i class="glyphicon glyphicon-flag"></i> Edit fields</a>
                            <a href="{{ path(base_route ~ '_show', {'product':item.id}) }}" class="btn btn-success"><i class="glyphicon glyphicon-eye-open"></i> Show</a>
                            {#<a href="{{ path(base_route ~ '_delete', {'id':item.id}) }}" disabled class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete product</a>#}
                        </span>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>

{% endblock %}